chore: update document and custom editor sample
opensumi/opensumi-module-samples pull request #18
Opened 2023-02-14 07:25 UTC by life2015

- update document for lan connect
- update custom editor sample

2023-02-14 07:27 UTC, erha19 requested changes

2023-02-14 07:27 UTC, erha19 commented on README.md
> +need to modify example/configs/webpack.browser.config.js
这里应该是线上容器环境下才需要修改的吧？

2023-02-28 07:58 UTC, erha19 commented on README.md
> +need to modify example/configs/webpack.browser.config.js
-> Need to modify `example/configs/webpack.browser.config.js`.

2023-03-23 07:33 UTC, life2015 commented on README.md
> +need to modify example/configs/webpack.browser.config.js
> 这里应该是线上容器环境下才需要修改的吧？

使用云研发的时候也需要修改

2023-03-23 07:37 UTC, erha19 approved these changes

2023-03-23 07:37 UTC, merged